### ISSUE TITLE
Doesn't work in production with more than 10 users on the app. 

### ISSUE THREAD

**Issue by mahavrilla** [jlondrejcka/Salesforce-Lightning-Component-Whos-Viewing-My-Record#1]
Our team was recently directed to this app on the app exchange. We tested in Dev, and everything worked great. When we deployed to production however, we couldn't get it to work. 

We kept seeing an `EMP API Proxy {}` error. Because the error is not stringified, locker service does not give us a glimpse into the error. An update would be to `JSON.Stringify(error)` so that we can see it. 

Once we were able to make the necessary changes and push to prod again we came across the actual error.

```
{"clientId":"<clientId>","channel":"/meta/subscribe","id":"3","subscription":"/event/whosViewing__e","error":"403::Organization total events daily limit exceeded","successful":false}
```

Salesforce says this is a limit that cannot be increased.
```
The maximum concurrent subscriber count for streaming API daily limits is 10 across all Salesforce organization editions. This is a static limit and cannot be increased with a support request.
```
https://help.salesforce.com/articleView?id=000270602&language=en_US&type=1

Therefore, just a heads up, that if you use this product an app that has more than 10 users, you will also experience this issue. If you have suggestions, I'd love to hear about them.

**Comment by jlondrejcka** [comment]
As stated this is limited to platform event limitations.
